const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const P=require('../../web/pc-preferences.js');
function fixture(){
 const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
 const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:0,checked:false,textContent:'',hidden:false,disabled:false,attrs:{},getAttribute(k){return this.attrs[k];},prepend(){}});return nodes.get(id);};
 const S={mobile:true},listeners={};let resets=0;
 const context={CloudPCPreferences:P,localStorage:storage,S,window:{},document:{createElement(){return{};},addEventListener(type,fn){listeners[type]=fn;}},$:node,mouse:{},latencyGuard:{reset(){resets++;}},desiredSettings:()=>({bitrate:S.bitrate,fps:S.fps,preset:S.preset,codec:S.codec,playoutDelay:Number(node('#latency-mode').value)}),setSwitch:(id,on)=>node(id).attrs['aria-checked']=String(on),selectButtons(){},updateCodecs(){S.codec='h264';},renderControls(){},toast(){},queueMicrotask:fn=>fn(),originalChanged(){},peer:null};
 vm.runInNewContext(fs.readFileSync(require.resolve('../../web/session-preferences.js'),'utf8'),context);
 return {S,node,storage,api:context.window.PCSessionPreferences,listeners,context};
}
test('actual player applies shared defaults before connection and isolates later PC overrides',()=>{const f=fixture();P.saveDefaults(f.storage,{preset:'2k60',fps:160,bitrate:35,volume:40,sound:true});f.api.connect('A');assert.equal(f.S.fps,160);assert.equal(f.S.preset,'2k60');assert.equal(f.node('#audio').volume,.4);assert.equal(f.node('#sound').getAttribute('aria-checked'),'true');f.S.fps=240;f.api.save();f.api.connect('B');assert.equal(f.S.fps,160);f.api.connect('A');assert.equal(f.S.fps,240);assert.equal(f.node('#preferences-source').textContent,'Tùy chỉnh riêng cho PC này');});
test('player saves desired quality rather than transient adaptation, follows changed defaults and resets',async()=>{const f=fixture();f.api.connect('A');f.S.bitrate=40;f.api.save();P.saveDefaults(f.storage,{fps:90,bitrate:25,volume:20});f.api.connect('A');assert.equal(f.S.bitrate,40);assert.equal(f.S.fps,90);assert.equal(f.node('#audio').volume,.2);assert.deepEqual(P.override(f.storage,'A'),{bitrate:40});await f.node('#reset-pc-preferences').onclick();assert.equal(f.S.bitrate,25);assert.deepEqual(P.override(f.storage,'A'),{});});
test('codec UI saves explicit changes; preview does not create PC overrides',()=>{const f=fixture();f.S.codec='av1';f.api.save();assert.equal(f.storage.getItem(P.key),null);f.api.connect('A');f.S.codec='av1';f.listeners.click({target:{id:'',closest:selector=>selector==='#codecs'?{}:null}});assert.equal(P.resolve(f.storage,'A').codec,'av1');});
test('automatic codec compatibility fallback never becomes a saved PC override',()=>{const f=fixture();P.saveDefaults(f.storage,{codec:'av1'});f.api.connect('A');f.context.updateCodecs();f.node('#audio-volume').value=40;f.api.save();assert.deepEqual(P.override(f.storage,'A'),{volume:40});assert.equal(P.resolve(f.storage,'A').codec,'av1');});
