(function(root){
  'use strict';
  const names={8:'Backspace',9:'Tab',13:'Enter',16:'Shift',17:'Ctrl',18:'Alt',19:'Pause',20:'Caps Lock',27:'Esc',32:'Space',33:'PgUp',34:'PgDn',35:'End',36:'Home',37:'←',38:'↑',39:'→',40:'↓',44:'PrtSc',45:'Ins',46:'Del',91:'Win L',92:'Win R',93:'Menu',106:'Num *',107:'Num +',109:'Num −',110:'Num .',111:'Num /',144:'Num Lock',145:'Scroll Lock',160:'Shift L',161:'Shift R',162:'Ctrl L',163:'Ctrl R',164:'Alt L',165:'Alt R',173:'Mute',174:'Vol −',175:'Vol +',179:'Play/Pause',186:';',187:'=',188:',',189:'-',190:'.',191:'/',192:'`',219:'[',220:'\\',221:']',222:"'",254:'Num Enter'};
  for(let k=48;k<=90;k++)if(k<=57||k>=65)names[k]=String.fromCharCode(k);
  for(let k=96;k<=105;k++)names[k]='Num '+(k-96);
  for(let k=112;k<=123;k++)names[k]='F'+(k-111);
  const label=keys=>keys.map(k=>names[k]||'VK '+k).join(' + ');
  const sections=[{name:'Chính',kind:'main',rows:[[27,...Array.from({length:12},(_,i)=>112+i)],[192,...'1234567890'.split('').map(c=>c.charCodeAt(0)),189,187,8],[9,...'QWERTYUIOP'.split('').map(c=>c.charCodeAt(0)),219,221,220],[20,...'ASDFGHJKL'.split('').map(c=>c.charCodeAt(0)),186,222,13],[160,...'ZXCVBNM'.split('').map(c=>c.charCodeAt(0)),188,190,191,161],[162,91,164,32,165,92,93,163]]},{name:'Điều hướng',kind:'navigation',rows:[[44,145,19],[45,36,33],[46,35,34],[38],[37,40,39]]},{name:'Cụm số',kind:'numpad',rows:[[144,111,106,109],[103,104,105,107],[100,101,102],[97,98,99,254],[96,110]]},{name:'Âm thanh',kind:'media',rows:[[173,174,175,179]]}];
  function board(className,onKey){const keyboard=document.createElement('div');keyboard.className='full-keyboard '+className;for(const section of sections){const group=document.createElement('section');group.className='keyboard-section '+section.kind;const heading=document.createElement('small');heading.textContent=section.name;group.append(heading);for(const row of section.rows){const line=document.createElement('div');line.className=className==='live-keyboard-board'?'live-keyboard-row':'key-picker-row';for(const vk of row){const b=document.createElement('button');b.type='button';b.dataset.vk=vk;b.textContent=section.kind==='numpad'?(vk===144?'Num':vk===254?'Enter':names[vk].replace(/^Num /,'')):vk===145?'Scroll':vk===20?'Caps':names[vk];b.setAttribute('aria-label','Phím '+names[vk]);onKey(b,vk);line.append(b);}group.append(line);}keyboard.append(group);}return keyboard;}
  let dialog,state,output,manual,error,mouseRow,padBoard,modeTabs;
  function choose(keys,vk,single){if(single)return keys.includes(vk)?[]:[vk];return keys.includes(vk)?keys.filter(k=>k!==vk):keys.length<6?[...keys,vk]:keys;}
  function refresh(){const pad=state.mode==='gamepad';output.textContent=pad?((root.CloudVirtualPad.label(state.padButtons)||'Chưa chọn nút')+'\nChạm nhiều nút để tạo tổ hợp, ví dụ A + RT. Bấm lại để bỏ chọn.'):(state.keys.length?label(state.keys):'Chạm một hoặc nhiều phím');manual.value=state.keys.length?state.keys.join(', '):'';for(const b of dialog.querySelectorAll('[data-vk]'))b.setAttribute('aria-pressed',String(state.keys.includes(Number(b.dataset.vk))));for(const b of dialog.querySelectorAll('[data-pad]'))b.setAttribute('aria-pressed',String(state.padButtons.includes(b.dataset.pad)));for(const b of modeTabs.children)b.setAttribute('aria-selected',String(b.dataset.mode===state.mode));for(const el of dialog.querySelectorAll('.full-keyboard,.mobile-key-board,.key-group-tabs,details'))el.hidden=pad;padBoard.hidden=!pad;mouseRow.hidden=pad||typeof state.onMouse!=='function';modeTabs.hidden=typeof state.onGamepad!=='function';dialog.querySelector('footer button').textContent=pad?(state.padButtons.length>1?'Dùng tổ hợp tay cầm':'Dùng nút tay cầm'):'Dùng phím này';}
  function build(){
    dialog=document.createElement('dialog');dialog.className='key-picker';dialog.setAttribute('aria-label','Bàn phím chọn nút');
    const header=document.createElement('header'),title=document.createElement('strong'),close=document.createElement('button');title.id='key-picker-title';close.type='button';close.textContent='×';close.setAttribute('aria-label','Đóng bàn phím');close.onclick=()=>dialog.close();header.append(title,close);dialog.append(header);
    modeTabs=document.createElement('div');modeTabs.className='binding-mode-tabs';modeTabs.setAttribute('role','tablist');modeTabs.setAttribute('aria-label','Loại điều khiển');for(const [mode,name] of [['keyboard','Bàn phím'],['gamepad','Tay cầm']]){const b=document.createElement('button');b.type='button';b.dataset.mode=mode;b.textContent=name;b.setAttribute('role','tab');b.onclick=()=>{state.mode=mode;error.textContent='';refresh();};modeTabs.append(b);}dialog.append(modeTabs);
    output=document.createElement('p');output.className='key-picker-selection';dialog.append(output);
    const keyboard=board('key-picker-board',(b,vk)=>{b.onclick=()=>{state.keys=choose(state.keys,vk,state.single);error.textContent='';refresh();};});
    dialog.append(keyboard);
    padBoard=document.createElement('div');padBoard.className='controller-picker';padBoard.innerHTML='<svg viewBox="0 0 368 349" aria-hidden="true"><path d="M81 125Q101 114 123 114H217Q244 114 265 130Q279 143 287 173L312 253Q320 283 312 306Q308 315 297 315Q286 315 273 306L240 276Q229 265 214 265H125Q109 265 98 277L70 304Q57 316 43 312Q29 309 24 291Q19 273 27 248L52 173Q61 139 81 125Z" fill="#fff" stroke="#c9d8ef" stroke-width="2"/><path d="M52 194L100 242Q109 251 125 251H214Q231 251 242 240L287 194M25 288Q39 314 63 300L96 270Q111 253 127 257H212Q231 254 244 269L276 301Q300 324 312 302" fill="none" stroke="#edf2fa" stroke-width="2"/><circle cx="97" cy="160" r="26" fill="#f8fbff" stroke="#c9d8ef" stroke-width="2"/><circle cx="211" cy="212" r="27" fill="#f8fbff" stroke="#c9d8ef" stroke-width="2"/><circle cx="133" cy="211" r="26" fill="#f8fbff" stroke="#c9d8ef" stroke-width="2"/><circle cx="244" cy="160" r="26" fill="#f8fbff" stroke="#c9d8ef" stroke-width="2"/></svg>';
    const layout={lt:[31,19.2],rt:[61.4,19.2],lb:[29.8,27.8],rb:[61.4,27.8],l3:[26.4,45.8],r3:[57.3,60.7],y:[66.3,40.5],x:[61,45.8],b:[71.6,45.8],a:[66.3,51.1],up:[36.1,55.1],left:[30.8,60.4],right:[41.4,60.4],down:[36.1,65.7]};
    for(const [name,[x,y]] of Object.entries(layout)){const b=document.createElement('button');b.type='button';b.dataset.pad=name;b.textContent=root.CloudVirtualPad?.labels[name]||name.toUpperCase();b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label','Tay cầm '+b.textContent);b.onclick=()=>{state.padButtons=choose(state.padButtons,name,false);error.textContent='';refresh();};padBoard.append(b);}dialog.append(padBoard);
    mouseRow=document.createElement('div');mouseRow.className='key-picker-row';for(const [name,action] of [['Chuột trái','left'],['Chuột phải','right'],['Chuột giữa','middle']]){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=()=>{state.onMouse?.(action);state.applied=true;dialog.close();};mouseRow.append(b);}dialog.append(mouseRow);
    const manualLabel=document.createElement('label');manualLabel.textContent='Nhập thủ công (R + T hoặc mã phím 82, 84)';manual=document.createElement('input');manual.type='text';manual.autocomplete='off';manualLabel.append(manual);const advanced=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Nhập phím bằng tay';advanced.append(summary,manualLabel);dialog.append(advanced);
    error=document.createElement('p');error.className='key-picker-error';error.setAttribute('role','alert');dialog.append(error);
    const footer=document.createElement('footer'),apply=document.createElement('button');apply.type='button';apply.textContent='Dùng phím này';apply.onclick=()=>{try{if(state.mode==='gamepad'){if(!state.padButtons.length)throw Error('Chạm một nút tay cầm để chọn.');state.onGamepad(state.padButtons);}else{const keys=CloudTouch.combo(manual.value);if(state.single&&keys.length!==1)throw Error('Chọn một phím cho hướng này.');state.onApply(keys);}state.applied=true;dialog.close();}catch(e){error.textContent=e.message;}};footer.append(apply);dialog.append(footer);
    dialog.addEventListener('close',()=>{if(!state.applied)state.onCancel?.();});
    dialog.addEventListener('pointerdown',e=>e.stopPropagation());dialog.addEventListener('keydown',e=>e.stopPropagation());document.body.append(dialog);
  }
  function open(options){if(!dialog)build();state={keys:[...(options.keys||[])],padButtons:root.CloudVirtualPad?.clean(options.padButtons)||[],mode:options.mode==='gamepad'&&options.onGamepad?'gamepad':'keyboard',single:options.single===true,onApply:options.onApply,onGamepad:options.onGamepad,onMouse:options.onMouse,onCancel:options.onCancel,applied:false};dialog.querySelector('#key-picker-title').textContent=options.title||'Chọn nút · bấm lại để bỏ chọn';error.textContent='';refresh();if(!dialog.open)dialog.showModal();}
  root.CloudKeyPicker={open,label,choose,sections,board};
  if(typeof module==='object')module.exports=root.CloudKeyPicker;
})(globalThis);
